### PR TITLE
net: dhcpv6: remove MTK_DHCPV6C_WIFI feature

### PR DESCRIPTION
**Pull request by ghost**
MTK extension MTK_DHCPV6C_WIFI is no longer necessary. Remove option
and functionality.

This reverts commit ccd52552b0ef ("HPV6: fix HPv6 onfig Error") and
4996bbf5c24b ("DHCPV6:Support DHCPV6 to Assign IPV6 Address")

Change-Id: I3a1ea546bd4006546a301e0fc0fed721ae5c507f
CR-Id: ALPS02210363
Signed-off-by: Yingjoe Chen <yingjoe.chen@mediatek.com>

### CODE REVIEW

**Comment by fire855** [comment]
The changes are good but you forgot 2 CONFIG_MTK_DHCPV6C_WIFI definitions in addrconf.c.
https://github.com/Moyster/android_kernel_jiayu_s3plus_n560a/blob/n-7.1.1/net/ipv6/addrconf.c
Also it would be good if this commit includes removing it from the defconfig too.

**Comment by ghost** [comment]
my bad, fixed. Feel free to squash

edit: original patch for ref : https://android-review.googlesource.com/#/c/177688/

**Comment by fire855** [comment]
Thanks but your last commit contains no change in defconfig

**Comment by ghost** [comment]
I should not make PR in a hurry while doing other things... fixed

edit: properly rebased

**Comment by fire855** [comment]
Thanks, now it's fine.

**Pull request merged**
